databases:
  - name: nlptosql-db
    databaseName: nlptosql
    user: nlptosql
    plan: free

services:
  - type: web
    name: nlp-to-sql-query
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn NLPtoSQLQuery.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nlptosql-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: "False"
      - key: GROQ_API_KEY
        sync: false # You'll set this manually in Render dashboard
